Fix tsc errors
I had hit these errors:

test/decorators/ConfigClass.spec.ts:169:29 - error TS2339: Property '__state' does not exist on type 'IConfigClassBase<unknown>'.

169     chai.expect((wc.clone().__state as any).main.value[0].__state.a.tags.name).to.deep.equal('web name');
                                ~~~~~~~

test/decorators/WebConfigClass.spec.ts:214:22 - error TS2339: Property 'clone' does not exist on type 'C & IConfigClassBase<unknown>'.

214       chai.expect((c.clone<C>().sub.arr[1] as any).toJSON({attachState: true})).to.deep.equal({
                         ~~~~~